# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from modules.Utils import Utils

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 400)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.centralVLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralVLayout.setObjectName("verticalLayout")
        self.headerWidget = QtWidgets.QWidget(self.centralwidget)
        self.headerWidget.setMinimumSize(QtCore.QSize(583, 36))
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 36))
        self.headerWidget.setStyleSheet("QWidget {\n"
"    border: 1px solid #222222;\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"}\n"
"QLabel {\n"
"    border: none;\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.headerWidget)
        self.headerHLayout.setContentsMargins(11, 11, -1, 11)
        self.headerHLayout.setObjectName("headerHLayout")
        self.circle_1 = QtWidgets.QFrame(self.headerWidget)
        self.circle_1.setEnabled(True)
        self.circle_1.setMinimumSize(QtCore.QSize(11, 11))
        self.circle_1.setMaximumSize(QtCore.QSize(11, 11))
        self.circle_1.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    background-color: #222222;\n"
"}")
        self.circle_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circle_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circle_1.setObjectName("circle_1")
        self.headerHLayout.addWidget(self.circle_1)
        self.circle_2 = QtWidgets.QFrame(self.headerWidget)
        self.circle_2.setMinimumSize(QtCore.QSize(11, 11))
        self.circle_2.setMaximumSize(QtCore.QSize(11, 11))
        self.circle_2.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    background-color: #0078D7;\n"
"}")
        self.circle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circle_2.setObjectName("circle_2")
        self.headerHLayout.addWidget(self.circle_2)
        self.circle_3 = QtWidgets.QFrame(self.headerWidget)
        self.circle_3.setMinimumSize(QtCore.QSize(11, 11))
        self.circle_3.setMaximumSize(QtCore.QSize(11, 11))
        self.circle_3.setStyleSheet("QFrame {\n"
"    border-radius: 5px;\n"
"    background-color: #F1E7CE;\n"
"}")
        self.circle_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circle_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circle_3.setObjectName("circle_3")
        self.headerHLayout.addWidget(self.circle_3)
        self.headerLabel = QtWidgets.QLabel(self.headerWidget)
        self.headerLabel.setMinimumSize(QtCore.QSize(217, 14))
        self.headerLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.headerHLayout.addWidget(self.headerLabel)
        self.centralVLayout.addWidget(self.headerWidget)
        self.bodyWidget = QtWidgets.QWidget(self.centralwidget)
        self.bodyWidget.setMinimumSize(QtCore.QSize(583, 335))
        self.bodyWidget.setStyleSheet("QWidget#bodyWidget {\n"
"    border: 1px solid #222222;\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"}")
        self.bodyWidget.setObjectName("bodyWidget")
        self.bodyVLayout = QtWidgets.QVBoxLayout(self.bodyWidget)
        self.bodyVLayout.setContentsMargins(-1, -1, -1, 0)
        self.bodyVLayout.setObjectName("bodyVLayout")
        self.titleLabel = QtWidgets.QLabel(self.bodyWidget)
        self.titleLabel.setMinimumSize(QtCore.QSize(201, 29))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.bodyVLayout.addWidget(self.titleLabel)
        self.langWidget = QtWidgets.QWidget(self.bodyWidget)
        self.langWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.langWidget.setObjectName("langWidget")
        self.langHLayout = QtWidgets.QHBoxLayout(self.langWidget)
        self.langHLayout.setContentsMargins(0, -1, 0, -1)
        self.langHLayout.setObjectName("langHLayout")
        self.fromlangWidget = QtWidgets.QFrame(self.langWidget)
        self.fromlangWidget.setMinimumSize(QtCore.QSize(225, 30))
        self.fromlangWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.fromlangWidget.setStyleSheet("QWidget#fromlangWidget {\n"
"    border: 1px solid #222222;\n"
"    border-radius: 15px;\n"
"    background-color: #0078D7;\n"
"}")
        self.fromlangWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fromlangWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fromlangWidget.setObjectName("fromlangWidget")
        self.fromlangHLayout = QtWidgets.QHBoxLayout(self.fromlangWidget)
        self.fromlangHLayout.setContentsMargins(15, 3, 15, 7)
        self.fromlangHLayout.setObjectName("fromlangHLayout")
        self.fromlangLabel = QtWidgets.QLabel(self.fromlangWidget)
        self.fromlangLabel.setMinimumSize(QtCore.QSize(45, 23))
        self.fromlangLabel.setMaximumSize(QtCore.QSize(45, 23))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(8)
        self.fromlangLabel.setFont(font)
        self.fromlangLabel.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.fromlangLabel.setObjectName("fromlangLabel")
        self.fromlangHLayout.addWidget(self.fromlangLabel)
        self.fromlangComboBox = QtWidgets.QComboBox(self.fromlangWidget)
        self.fromlangComboBox.setMinimumSize(QtCore.QSize(0, 23))
        self.fromlangComboBox.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(8)
        self.fromlangComboBox.setFont(font)
        self.fromlangComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #0078D7;\n"
"    border-radius: 14px;\n"
"    color: #FFFFFF;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(D:/screen-translator/assets/icon/white_arrow.svg);\n"
"    height: 100%;\n"
"}\n"
"QComboBox::drop-down {\n"
"   border: 0px;\n"
"}")
        self.fromlangComboBox.setObjectName("fromlangComboBox")
        lang_list = list(Utils.get_en_languages().keys())
        for lang in lang_list:
            self.fromlangComboBox.addItem(lang)
        self.fromlangComboBox.setCurrentIndex(3)
        self.fromlangHLayout.addWidget(self.fromlangComboBox)
        self.langHLayout.addWidget(self.fromlangWidget)
        self.switchlangButton = QtWidgets.QPushButton(self.langWidget)
        self.switchlangButton.setMinimumSize(QtCore.QSize(40, 40))
        self.switchlangButton.setMaximumSize(QtCore.QSize(40, 40))
        self.switchlangButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switchlangButton.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    image: url(D:/screen-translator/assets/icon/switch.svg);\n"
"}")
        self.switchlangButton.setText("")
        self.switchlangButton.setObjectName("switchlangButton")
        self.langHLayout.addWidget(self.switchlangButton)
        self.tolangWidget = QtWidgets.QFrame(self.langWidget)
        self.tolangWidget.setMinimumSize(QtCore.QSize(225, 30))
        self.tolangWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tolangWidget.setStyleSheet("QWidget#tolangWidget {\n"
"    border: 1px solid #222222;\n"
"    border-radius: 15px;\n"
"    background-color: #F1E7CE;\n"
"}")
        self.tolangWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tolangWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tolangWidget.setObjectName("tolangWidget")
        self.tolangHLayout = QtWidgets.QHBoxLayout(self.tolangWidget)
        self.tolangHLayout.setContentsMargins(15, 3, 15, 7)
        self.tolangHLayout.setObjectName("tolangHLayout")
        self.tolangLabel = QtWidgets.QLabel(self.tolangWidget)
        self.tolangLabel.setMinimumSize(QtCore.QSize(22, 23))
        self.tolangLabel.setMaximumSize(QtCore.QSize(22, 23))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(8)
        self.tolangLabel.setFont(font)
        self.tolangLabel.setObjectName("tolangLabel")
        self.tolangHLayout.addWidget(self.tolangLabel)
        self.tolangComboBox = QtWidgets.QComboBox(self.tolangWidget)
        self.tolangComboBox.setMinimumSize(QtCore.QSize(0, 23))
        self.tolangComboBox.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        self.tolangComboBox.setFont(font)
        self.tolangComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #F1E7CE;\n"
"    border-radius: 14px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(D:/screen-translator/assets/icon/arrow.svg);\n"
"    height: 100%;\n"
"}\n"
"QComboBox::drop-down {\n"
"   border: 0px;\n"
"}")
        self.tolangComboBox.setObjectName("tolangComboBox")
        lang_list = list(Utils.get_en_languages().keys())
        for lang in lang_list:
            self.tolangComboBox.addItem(lang)
        self.tolangComboBox.setCurrentIndex(12)
        self.tolangHLayout.addWidget(self.tolangComboBox)
        self.langHLayout.addWidget(self.tolangWidget)
        self.bodyVLayout.addWidget(self.langWidget)
        self.settingsWidget = QtWidgets.QWidget(self.bodyWidget)
        self.settingsWidget.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.settingsWidget.setFont(font)
        self.settingsWidget.setStyleSheet("")
        self.settingsWidget.setObjectName("settingsWidget")
        self.settingsHLayout = QtWidgets.QHBoxLayout(self.settingsWidget)
        self.settingsHLayout.setObjectName("settingsHLayout")
        self.settingsHLayout.setContentsMargins(0, 11, 0, 11)
        self.settingsFrame = QtWidgets.QFrame(self.settingsWidget)
        self.settingsFrame.setMinimumSize(QtCore.QSize(311, 181))
        self.settingsFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settingsFrame.setStyleSheet("QFrame {\n"
"    border: 1px solid #222222;\n"
"    border-radius: 15px;\n"
"}\n"
"QLabel {\n"
"    border: none;\n"
"}")
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.settingsVLayout = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.settingsVLayout.setContentsMargins(-1, 10, -1, 50)
        self.settingsVLayout.setObjectName("settingsVLayout")
        self.translatorFrame = QtWidgets.QFrame(self.settingsFrame)
        self.translatorFrame.setMinimumSize(QtCore.QSize(0, 33))
        self.translatorFrame.setMaximumSize(QtCore.QSize(16777215, 33))
        self.translatorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.translatorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.translatorFrame.setObjectName("translatorFrame")
        self.translatorHLayout = QtWidgets.QHBoxLayout(self.translatorFrame)
        self.translatorHLayout.setContentsMargins(15, 3, 15, 7)
        self.translatorHLayout.setObjectName("translatorHLayout")
        self.translatorLabel = QtWidgets.QLabel(self.translatorFrame)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        self.translatorLabel.setFont(font)
        self.translatorLabel.setStyleSheet("")
        self.translatorLabel.setObjectName("translatorLabel")
        self.translatorHLayout.addWidget(self.translatorLabel)
        self.translatorComboBox = QtWidgets.QComboBox(self.translatorFrame)
        self.translatorComboBox.setMinimumSize(QtCore.QSize(165, 23))
        self.translatorComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.translatorComboBox.setStyleSheet("QComboBox {\n"
"    background-color: transparent;\n"
"    border-radius: 14px;\n"
"    font-family: \"Cascadia Mono Light\";\n"
"    font-size: 13px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(D:/screen-translator/assets/icon/arrow.svg);\n"
"    height: 100%;\n"
"}\n"
"QComboBox::drop-down {\n"
"   border: 0px;\n"
"}")
        self.translatorComboBox.setObjectName("translatorComboBox")
        translators = ['Google Translate', 'MyMemoryTranslator', 'Deepl', 'LibreTranslate']
        for translator in translators:
            self.translatorComboBox.addItem(translator)
        self.translatorHLayout.addWidget(self.translatorComboBox)
        self.settingsVLayout.addWidget(self.translatorFrame)
        self.screenrefreshFrame = QtWidgets.QFrame(self.settingsFrame)
        self.screenrefreshFrame.setMinimumSize(QtCore.QSize(0, 33))
        self.screenrefreshFrame.setMaximumSize(QtCore.QSize(16777215, 33))
        self.screenrefreshFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.screenrefreshFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.screenrefreshFrame.setObjectName("screenrefreshFrame")
        self.screenrefreshHLayout = QtWidgets.QHBoxLayout(self.screenrefreshFrame)
        self.screenrefreshHLayout.setContentsMargins(15, 3, 15, 7)
        self.screenrefreshHLayout.setObjectName("screenrefreshHLayout")
        self.screenrefreshLabel = QtWidgets.QLabel(self.screenrefreshFrame)
        self.screenrefreshLabel.setMinimumSize(QtCore.QSize(162, 17))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        self.screenrefreshLabel.setFont(font)
        self.screenrefreshLabel.setStyleSheet("")
        self.screenrefreshLabel.setObjectName("screenrefreshLabel")
        self.screenrefreshHLayout.addWidget(self.screenrefreshLabel)
        self.screenrefreshComboBox = QtWidgets.QComboBox(self.screenrefreshFrame)
        self.screenrefreshComboBox.setMinimumSize(QtCore.QSize(10, 23))
        self.screenrefreshComboBox.setStyleSheet("QComboBox {\n"
"    background-color: transparent;\n"
"    border-radius: 14px;\n"
"    font-family: \"Cascadia Mono Light\";\n"
"    font-size: 13px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(D:/screen-translator/assets/icon/arrow.svg);\n"
"    height: 100%;\n"
"}\n"
"QComboBox::drop-down {\n"
"   border: 0px;\n"
"}")
        self.screenrefreshComboBox.setObjectName("screenrefreshComboBox")
        for x in (0.4 + 0.2*i for i in range(24) if 0.1 + 0.2*i <= 5.0):
             self.screenrefreshComboBox.addItem(f"{x:.1f} sec")
        self.screenrefreshHLayout.addWidget(self.screenrefreshComboBox)
        self.settingsVLayout.addWidget(self.screenrefreshFrame)
        self.settingsHLayout.addWidget(self.settingsFrame)
        self.tipsFrame = QtWidgets.QFrame(self.settingsWidget)
        self.tipsFrame.setMinimumSize(QtCore.QSize(160, 181))
        self.tipsFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tipsFrame.setStyleSheet("QFrame#tipsFrame {\n"
"    border: 1px solid #222222;\n"
"    border-top-left-radius: 15px;\n"
"    border-top-right-radius: 15px;\n"
"}\n"
"QLabel {\n"
"    border: none;\n"
"}")
        self.tipsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tipsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tipsFrame.setObjectName("tipsFrame")
        self.tipsVLayout = QtWidgets.QVBoxLayout(self.tipsFrame)
        self.tipsVLayout.setContentsMargins(10, 10, 10, 10)
        self.tipsVLayout.setObjectName("tipsVLayout")
        self.tipscontentFrame_1 = QtWidgets.QFrame(self.tipsFrame)
        self.tipscontentFrame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tipscontentFrame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tipscontentFrame_1.setObjectName("tipscontentFrame_1")
        self.tipscontentHLayout_1 = QtWidgets.QHBoxLayout(self.tipscontentFrame_1)
        self.tipscontentHLayout_1.setContentsMargins(0, 0, 0, 0)
        self.tipscontentHLayout_1.setObjectName("tipscontentHLayout_1")
        self.tipscontentLabel_1 = QtWidgets.QLabel(self.tipscontentFrame_1)
        self.tipscontentLabel_1.setMinimumSize(QtCore.QSize(139, 56))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        self.tipscontentLabel_1.setFont(font)
        self.tipscontentLabel_1.setScaledContents(False)
        self.tipscontentLabel_1.setWordWrap(True)
        self.tipscontentLabel_1.setObjectName("tipscontentLabel_1")
        self.tipscontentHLayout_1.addWidget(self.tipscontentLabel_1)
        self.tipsVLayout.addWidget(self.tipscontentFrame_1)
        self.lineFrame = QtWidgets.QFrame(self.tipsFrame)
        self.lineFrame.setMinimumSize(QtCore.QSize(0, 1))
        self.lineFrame.setMaximumSize(QtCore.QSize(16777215, 1))
        self.lineFrame.setStyleSheet("QFrame {\n"
"    border: 1px solid #222222;\n"
"    padding: 10px;\n"
"}")
        self.lineFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineFrame.setObjectName("lineFrame")
        self.tipsVLayout.addWidget(self.lineFrame)
        self.tipscontentFrame_2 = QtWidgets.QFrame(self.tipsFrame)
        self.tipscontentFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tipscontentFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tipscontentFrame_2.setObjectName("tipscontentFrame_2")
        self.tipscontentVLayout_2 = QtWidgets.QVBoxLayout(self.tipscontentFrame_2)
        self.tipscontentVLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tipscontentVLayout_2.setObjectName("tipscontentVLayout_2")
        self.tipscontentLabel_2 = QtWidgets.QLabel(self.tipscontentFrame_2)
        self.tipscontentLabel_2.setMinimumSize(QtCore.QSize(139, 40))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        self.tipscontentLabel_2.setFont(font)
        self.tipscontentLabel_2.setWordWrap(True)
        self.tipscontentLabel_2.setObjectName("tipscontentLabel_2")
        self.tipscontentVLayout_2.addWidget(self.tipscontentLabel_2)
        self.resetButton = QtWidgets.QPushButton(self.tipscontentFrame_2)
        self.resetButton.setMinimumSize(QtCore.QSize(70, 22))
        self.resetButton.setMaximumSize(QtCore.QSize(70, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setStyleSheet("QPushButton {\n"
"    background-color: #0078D7;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #222222;\n"
"    border-radius: 11px;\n"
"}")
        self.resetButton.setObjectName("pushButton")
        self.tipscontentVLayout_2.addWidget(self.resetButton, 0, QtCore.Qt.AlignHCenter)
        self.tipsVLayout.addWidget(self.tipscontentFrame_2)
        self.settingsHLayout.addWidget(self.tipsFrame)
        self.switchlangFrame = QtWidgets.QFrame(self.settingsWidget)
        self.switchlangFrame.setMinimumSize(QtCore.QSize(30, 0))
        self.switchlangFrame.setMaximumSize(QtCore.QSize(30, 16777215))
        self.switchlangFrame.setStyleSheet("")
        self.switchlangFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.switchlangFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.switchlangFrame.setObjectName("switchlangFrame")
        self.switchlangVLayout = QtWidgets.QVBoxLayout(self.switchlangFrame)
        self.switchlangVLayout.setContentsMargins(0, 0, 0, 0)
        self.switchlangVLayout.setObjectName("switchlangVLayout")
        self.enButton = QtWidgets.QPushButton(self.switchlangFrame)
        self.enButton.setMinimumSize(QtCore.QSize(27, 27))
        self.enButton.setMaximumSize(QtCore.QSize(27, 27))
        self.enButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #222222;\n"
"    border-radius: 13px;\n"
"    background-color: #F1E7CE;\n"
"}\n"
"QLabel {\n"
"    border: none;\n"
"}")
        self.enButton.setObjectName("enButton")
        self.switchlangVLayout.addWidget(self.enButton)
        self.ruButton = QtWidgets.QPushButton(self.switchlangFrame)
        self.ruButton.setMinimumSize(QtCore.QSize(27, 27))
        self.ruButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ruButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #222222;\n"
"    border-radius: 13px;\n"
"}\n"
"QLabel {\n"
"    border: none;\n"
"}")
        self.ruButton.setObjectName("ruButton")
        self.switchlangVLayout.addWidget(self.ruButton)
        self.settingsHLayout.addWidget(self.switchlangFrame, 0, QtCore.Qt.AlignBottom)
        self.bodyVLayout.addWidget(self.settingsWidget)
        self.footerWidget = QtWidgets.QWidget(self.bodyWidget)
        self.footerWidget.setMinimumSize(QtCore.QSize(0, 53))
        self.footerWidget.setObjectName("footerWidget")
        self.footerVLayout = QtWidgets.QVBoxLayout(self.footerWidget)
        self.footerVLayout.setObjectName("footerVLayout")
        self.footerLabel = QtWidgets.QLabel(self.footerWidget)
        self.footerLabel.setMinimumSize(QtCore.QSize(0, 12))
        self.footerLabel.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(6)
        self.footerLabel.setFont(font)
        self.footerLabel.setObjectName("footerLabel")
        self.footerVLayout.addWidget(self.footerLabel, 0, QtCore.Qt.AlignBottom)
        self.bodyVLayout.addWidget(self.footerWidget)
        self.centralVLayout.addWidget(self.bodyWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rosetta"))
        self.headerLabel.setText(_translate("MainWindow", "ROSETTA!@ / #Translator"))
        self.titleLabel.setText(_translate("MainWindow", "Screen Translator"))
        self.fromlangLabel.setText(_translate("MainWindow", "From:"))
        self.tolangLabel.setText(_translate("MainWindow", "To:"))
        self.translatorLabel.setText(_translate("MainWindow", "Translator:"))
        self.screenrefreshLabel.setText(_translate("MainWindow", "Screen refresh rate:"))
        self.tipscontentLabel_1.setText(_translate("MainWindow", "<html><head/><body><p>Press the <span style=\" font-style:italic; color:#0078d7;\">PrtSc</span> hotkey to capture the screen and then translate it in real time.</p></body></html>"))
        self.tipscontentLabel_2.setText(_translate("MainWindow", "To reset existing settings, click -"))
        self.resetButton.setText(_translate("MainWindow", "reset"))
        self.enButton.setText(_translate("MainWindow", "EN"))
        self.ruButton.setText(_translate("MainWindow", "RU"))
        self.footerLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#818181;\">1.10 | mewbaeru 2025</span></p></body></html>"))